stages:
  - prepare
  - test
  - build
  - artifact

variables:
  UNITY_CI_IMAGE: unityci/editor
  IMAGE_VERSION: 1
  UNITY_DIR: devopsdays_demo

image: $UNITY_CI_IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

get-unity-version:
  image: alpine
  stage: prepare
  variables:
    GIT_DEPTH: 1
  script:
    - echo $CI_PROJECT_DIR
    - echo UNITY_VERSION=$(cat $UNITY_DIR/ProjectSettings/ProjectVersion.txt | grep "m_EditorVersion:.*" | awk '{ print $2}') | tee prepare.env
  artifacts:
    reports:
      dotenv: prepare.env

test:
  stage: test
  needs:
    - job: get-unity-version
      artifacts: true
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

build:windows:
  stage: build
  needs: 
    - job: test
    - job: get-unity-version
      artifacts: true
  script:
    - echo "Building for Windows"

build:android:
  stage: build
  needs: 
    - job: test
    - job: get-unity-version
      artifacts: true
  script:
    - echo "Building for Android"

expose-artifact:windows:
  stage: artifact
  needs:
    - job: test
    - job: build:windows
      artifacts: true
    - job: get-unity-version
      artifacts: true
  script:
    - echo "Exposing build artifact for Windows"
  
expose-artifact:android:
  stage: artifact
  needs:
    - job: test
    - job: build:android
      artifacts: true
    - job: get-unity-version
      artifacts: true
  script:
    - echo "Exposing build artifact for Android"

