stages:
  - test
  - build
  - artifact


test:
  stage: test
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

buildWindows:
  stage: build
  needs: test
  script:
    - echo "Building for Windows"

buildAndroid:
  stage: build
  needs: test
  script:
    - echo "Building for Android"

exposeWindowsArtifact:
  stage: artifact
  needs: buildWindows
  script:
    - echo "Exposing build artifact for Windows"
  
exposeAndroidArtifact:
  stage: artifact
  needs: buildAndroid
  script:
    - echo "Exposing build artifact for Android"

