stages:
  - test
  - build
  - artifact

variables:
  UNITY_CI_IMAGE: unityci/editor
  VERSION: 1

image: $UNITY_CI_IMAGE:$VERSION

test:
  stage: test
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

build:windows:
  stage: build
  needs: [test]
  script:
    - echo "Building for Windows"

build:android:
  stage: build
  needs: [test]
  script:
    - echo "Building for Android"

exposeWindowsArtifact:
  stage: artifact
  needs: [build:windows]
  script:
    - echo "Exposing build artifact for Windows"
  
exposeAndroidArtifact:
  stage: artifact
  needs: [build:android]
  script:
    - echo "Exposing build artifact for Android"

