image: atlassian/default-image:3

definitions:
  scripts:
    import_env_variables: &import_env_variables
      source environment_setup.sh
    unity_before_script: &unity_before_script
      chmod +x ./ci/before-script.sh && ./ci/before-script.sh
    set_testing_type_as_NUNIT: &set_testing_type_as_NUNIT
      export TESTING_TYPE=NUNIT
    run_tests: &run_tests
      chmod +x ./ci/test.sh && ./ci/test.sh
    run_build: &run_build
      chmod +x ./ci/build.sh && ./ci/build.sh
  caches:
    build-cache-windows: $BITBUCKET_CLONE_DIR/devopsdays_demo/Library/
    build-cache-android: $BITBUCKET_CLONE_DIR/devopsdays_demo/Library/
  steps:
    - step: &set_up_environment_vars
        name: Set up environment variables
        script:
          - echo "export UNITY_DIR=$BITBUCKET_CLONE_DIR/devopsdays_demo" >> environment_setup.sh
          - echo "export CI_PROJECT_DIR=$BITBUCKET_CLONE_DIR" >> environment_setup.sh
          - echo "export CI_PROJECT_NAME=$BITBUCKET_REPO_FULL_NAME" >> environment_setup.sh
          - echo "Environment variables have been set-up"
        artifacts:
          - environment_setup.sh
    - step: &test_playmode
        name: Test (Playmode)
        image: unityci/editor:2022.3.5f1-base-1
        script:
          - *unity_before_script
          - *import_env_variables
          - *set_testing_type_as_NUNIT
          - export TEST_PLATFORM=playmode
          - *run_tests
    - step: &test_editmode
        name: Test (Editmode)
        image: unityci/editor:2022.3.5f1-base-1
        script:
          - *unity_before_script
          - *import_env_variables
          - *set_testing_type_as_NUNIT
          - export TEST_PLATFORM=editmode
          - *run_tests
    - step: &build_windows
        name: Build (Windows)
        image: unityci/editor:2022.3.5f1-windows-mono-1
        caches:
          - build-cache-windows
        size: 2x
        script:
          - *unity_before_script
          - *import_env_variables
          - export BUILD_TARGET=StandaloneWindows64
          - export BUILD_NAME=Build-StandaloneWindows64-$BITBUCKET_COMMIT-$BITBUCKET_BRANCH
          - *run_build
          - zip -r Build-StandaloneWindows64.zip devopsdays_demo/Builds/StandaloneWindows64
        depends:
          - Test (Playmode)
          - Test (Editmode)
        artifacts:
          - Build-StandaloneWindows64.zip
    - step: &build_android
        name: Build (Android)
        image: unityci/editor:2022.3.5f1-android-1
        caches:
          - build-cache-android
        size: 2x
        script:
          - *unity_before_script
          - *import_env_variables
          - export BUILD_TARGET=Android
          - export BUILD_NAME=Build-Android-$BITBUCKET_COMMIT-$BITBUCKET_BRANCH
          - *run_build
          - zip -r Build-Android.zip devopsdays_demo/Builds/Android
        depends:
          - Test (Playmode)
          - Test (Editmode)
        artifacts:
          - Build-Android.zip

pipelines:
  branches:
    release-*:
      - step: *set_up_environment_vars
      - parallel:
        - step: *test_playmode
        - step: *test_editmode
      - parallel:
        - step: *build_windows
        - step: *build_android
    main:  
      - step: *set_up_environment_vars
      - parallel:
        - step: *test_playmode
        - step: *test_editmode
      - parallel:
        - step: *build_windows
        - step: *build_android
    feature-*:
      - step: *set_up_environment_vars
      - parallel:
        - step: *test_playmode
        - step: *test_editmode
      - parallel:
        - step: 
            name: "Build (Windows) - Manual"
            trigger: manual
            script:
              - *build_windows
        - step: 
            name: "Build (Android) - Manual"
            trigger: manual
            script:
              - *build_android