image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: "Get unity version"
        script:
          - echo "Fetching unity version"

    - step:
        name: "Test (Playmode)"
        script:
          - echo "Playmode testing goes here"

    - step:
        name: "Test (Editmode)"
        script:
          - echo "Editmode testing goes here"

    - step:
        name: "Build (Windows)"
        script:
          - echo "Build for windows goes here"
    
    - step:
        name: "Build (Android)"
        script:
          - echo "Build for android goes here"