image: atlassian/default-image:3

definitions:
  variables:
    UNITY_CI_IMAGE: unityci/editor
    IMAGE_VERSION: 1
    UNITY_VERSION: 2022.3.5f1
  scripts: 
    import_env_variables: &import_env_variables
      source environment_setup.sh
    unity_before_script: &unity_before_script
      chmod +x ./ci/before-script.sh && ./ci/before-script.sh
    set_testing_type_as_NUNIT: &set_testing_type_as_NUNIT
      export TESTING_TYPE=NUNIT
    run_tests: &run_tests
      chmod +x ./ci/test.sh && ./ci/test.sh
    run_build: &run_build
      chmod +x ./ci/build.sh && ./ci/build.sh
  caches:
    unity-cache: $BITBUCKET_CLONE_DIR/devopsdays_demo/Library/

pipelines:
  default:
    # Stage: Prepare
    - step:
        name: Set up environment variables
        script:
          - echo "export UNITY_DIR=$BITBUCKET_CLONE_DIR/devopsdays_demo" >> environment_setup.sh
          - echo "export CI_PROJECT_DIR=$BITBUCKET_CLONE_DIR" >> environment_setup.sh
          - echo "export CI_PROJECT_NAME=$BITBUCKET_REPO_FULL_NAME" >> environment_setup.sh
          - echo "Environment variables have been set-up"
        artifacts:
          - environment_setup.sh

    # Stage: Test
    # - parallel:
    #   - step:
    #       name: Test (Playmode)
    #       image: unityci/editor:2022.3.5f1-base-1
    #       caches:
    #         - unity-cache
    #       script:
    #         - *unity_before_script
    #         - *import_env_variables
    #         - *set_testing_type_as_NUNIT
    #         - export TEST_PLATFORM=playmode
    #         - *run_tests
    #   - step:
    #       name: Test (Editmode)
    #       image: unityci/editor:2022.3.5f1-base-1
    #       caches:
    #         - unity-cache
    #       script:
    #         - *unity_before_script
    #         - *import_env_variables
    #         - *set_testing_type_as_NUNIT
    #         - export TEST_PLATFORM=editmode
    #         - *run_tests

    # Stage: Build
    - parallel:
      # - step:
      #     name: Build (Android)
      #     image: unityci/editor:2022.3.5f1-android-1
      #     caches:
      #       - unity-cache
      #     size: 2x
      #     script:
      #       - *unity_before_script
      #       - *import_env_variables
      #       - export BUILD_TARGET=Android
      #       - export BUILD_NAME=Build-Android-$BITBUCKET_COMMIT-$BITBUCKET_BRANCH
      #       - *run_build
      #     depends:
      #       - Test (Playmode)
      #       - Test (Editmode)
      #     artifacts:
      #       - devopsdays_demo/Builds/Android

      - step:
          name: Build (Windows)
          image: unityci/editor:2022.3.5f1-windows-mono-1
          caches:
            - unity-cache
          size: 2x
          script:
            - *unity_before_script
            - *import_env_variables
            - export BUILD_TARGET=StandaloneWindows64
            - export BUILD_NAME=Build-StandaloneWindows64-$BITBUCKET_COMMIT-$BITBUCKET_BRANCH
            - *run_build
            - tar -cf Build-StandaloneWindows64.zip devopsdays_demo/Builds/StandaloneWindows64
            - ls
          depends:
            - Test (Playmode)
            - Test (Editmode)
          artifacts:
            - environment_setup.sh
            - Build-StandaloneWindows64.zip