image: atlassian/default-image:3

definitions:
  variables:
    UNITY_CI_IMAGE: unityci/editor
    IMAGE_VERSION: 1
    UNITY_VERSION: 2022.3.5f1
  scripts: 
    import_env_variables: &import_env_variables
      source export.sh
    unity_before_script: &unity_before_script
      chmod +x ./ci/before-script.sh && ./ci/before-script.sh
    run_tests: &run_tests
      chmod +x ./ci/test.sh && ./ci/test.sh
    
  
  # steps:
  #       name: Unity before script
  #       script:
  #         - echo "Running the before script..."
  #         - chmod +x ./ci/before-script.sh && ./ci/before-script.sh
  #         - echo "Before script done."
  #   - step: &set_up_environment
  #     - source export.sh

commonScript: &commonScript
  script:
    - echo "common script"


pipelines:
  default:
    # Stage: Prepare
    - step:
        name: Set up environment variables
        script:v

          - echo "$UNITY_LICENSE"
          - echo "$UNITY_USERNAME"
          - echo "$UNITY_PASSWORD"

          - echo "export UNITY_DIR=$BITBUCKET_CLONE_DIR/devopsdays_demo" >> export.sh
          - echo "export CI_PROJECT_DIR=$BITBUCKET_CLONE_DIR" >> export.sh
          - echo "export CI_PROJECT_NAME=$BITBUCKET_REPO_FULL_NAME" >> export.sh
          - echo "Environment variables have been set-up"
          - cat export.sh
        artifacts: # define the artifacts to be passed to each future step
          - export.sh

    # Stage: Test
    # - parallel:
    #   - step:
    #       name: Test (Playmode)
    #       image: unityci/editor:2022.3.5f1-base-1
    #       script:
    #         - *unity_before_script
    #         - *import_env_variables
    #         - export TEST_PLATFORM=editmode
    #         - export TESTING_TYPE=NUNIT
    #         - *run_tests
      # - step:
      #     name: Test (Editmode)
      #     # image: unityci/editor:2022.3.5f1-base-1
      #     # <<: *unity_before_script
      #     script:
      #       - *unity_before_script
      #       - *import_env_variables
      #       - export TEST_PLATFORM=editmode
      #       - export TESTING_TYPE=NUNIT
      #       - *run_tests
            # - chmod +x ./ci/test.sh && ./ci/test.sh

    # Stage: Build
    # - parallel:
    #   - step:
    #       name: Build (Windows)
    #       # image: unityci/editor:2022.3.5f1-windows-mono-1
    #       script:
    #         - echo "Build for windows goes here"
    #       depends:
    #         - Test (Playmode)
    #         - Test (Editmode)
      
      # - step:
      #     name: Build (Android)
      #     # image: unityci/editor:2022.3.5f1-android-1
      #     script:
      #       - echo "Build for android goes here"
      #     depends:
      #       - Test (Playmode)
      #       - Test (Editmode)