image: atlassian/default-image:3

definitions:
  variables:
    UNITY_CI_IMAGE: unityci/editor
    IMAGE_VERSION: 1
    UNITY_VERSION: 2022.3.5f1

  scripts: 
    common_scripts: &common_scripts
      - echo "This is a shared script."
  
  # steps:
  #   - step: &unity_before_script
  #       name: Unity before script
  #       script:
  #         - echo "Running the before script..."
  #         - chmod +x ./ci/before-script.sh && ./ci/before-script.sh
  #         - echo "Before script done."
  #   - step: &set_up_environment
  #     - source export.sh


pipelines:
  default:
    # Stage: Prepare
    - step:
        name: Set up environment variables
        script:
          - echo "export UNITY_DIR=$BITBUCKET_CLONE_DIR/devopsdays_demo" >> export.sh
          - echo "export CI_PROJECT_DIR=$BITBUCKET_CLONE_DIR" >> export.sh
          - echo "export CI_PROJECT_NAME=$BITBUCKET_REPO_FULL_NAME" >> export.sh
          - echo "Environment variables have been set-up"
          - cat export.sh
        artifacts: # define the artifacts to be passed to each future step
          - export.sh

    # Stage: Test
    - parallel:
      - step:
          name: Test (Playmode)
          image: unityci/editor:2022.3.5f1-base-1
          script:
            - *common_scripts
            - export TEST_PLATFORM=playmode
            - export TESTING_TYPE=NUNIT
            # - *set_up_environment
            # - *unity_before_script
            # - chmod +x ./ci/test.sh && ./ci/test.sh

      - step:
          name: Test (Editmode)
          # image: unityci/editor:2022.3.5f1-base-1
          # <<: *unity_before_script
          script:
            - source export.sh 
            - export TEST_PLATFORM=editmode
            - export TESTING_TYPE=NUNIT
            # - chmod +x ./ci/test.sh && ./ci/test.sh


    # Stage: Build
    - parallel:
      - step:
          name: Build (Windows)
          # image: unityci/editor:2022.3.5f1-windows-mono-1
          script:
            - echo "Build for windows goes here"
          depends:
            - Test (Playmode)
            - Test (Editmode)
      
      - step:
          name: Build (Android)
          # image: unityci/editor:2022.3.5f1-android-1
          script:
            - echo "Build for android goes here"
          depends:
            - Test (Playmode)
            - Test (Editmode)