name: Continuous Integration
on: [push]
jobs:

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   permissions: write-all
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Run tests
  #       uses: game-ci/unity-test-runner@v2
  #       env:
  #         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #       with:
  #         projectPath: devopsdays_demo/
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}
  
  buildWindows:
    name: Build (Windows)
    # needs: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # Cache
      - uses: actions/cache@v3
        with:
          path: devopsdays_demo/Library
          key: Library-DevOpsDaysDemo-Windows
          restore-keys: |
            Library-MyProjectName-
            Library-
      # Build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: devopsdays_demo/
      # Expose build artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: build/StandaloneWindows64
  buildAndroid:
    name: Build (Android)
    # needs: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # Cache
      - uses: actions/cache@v3
        with:
          path: devopsdays_demo/Library
          key: Library-DevOpsDaysDemo-Android
          restore-keys: |
            Library-MyProjectName-
            Library-
      # Free up disk space (Android only)
      # - name: Free-up disk space (for Android only)
      #   uses: jlumbroso/free-disk-space@v1.2.0
      # Build
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: devopsdays_demo/
      # Expose build artifact
      - name: Expose as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build-Android
          path: build/Android